# ===========================================
# JOB 1: Collect current workload snapshots
# ===========================================
---
apiVersion: batch/v1
kind: Job
metadata:
  name: collect-snapshot
  namespace: energy
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: podpower-read
      restartPolicy: Never
      containers:
      - name: collect
        # Replace sha-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX with the commit-specific tag
        # emitted by CI for this build (ghcr.io/...:sha-<commit-sha>).
        image: ghcr.io/mskazemi/k8spodpcp:sha-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        imagePullPolicy: IfNotPresent
        args:
          - /bin/sh
          - -c
          - |
            set -e
            echo "▶ Step 1: Collecting live K8s objects"
            timeout 30s python3 k8s_collect.py watch \
              --kinds Deployment Job CronJob Pod \
              --emit-initial \
              --suppress-tls-warnings \
              --output /data/in.ndjson || code=$?; code=${code:-0}; if [ "$code" != "0" ] && [ "$code" != "124" ]; then exit "$code"; fi

            echo "▶ Step 2: Fitting or reusing encoder"
            if [ ! -f /data/encoder.joblib ]; then
              python3 k8s_encode.py fit \
                --input /data/in.ndjson \
                --out /data/encoder.joblib \
                --no-sbert
            fi

            echo "▶ Step 3: Transforming features"
            python3 k8s_encode.py transform \
              --input /data/in.ndjson \
              --encoder /data/encoder.joblib \
              --out /data/features.parquet
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: podpower-data
