# ===========================================
# JOB 3: Join features and labels
# ===========================================
---
apiVersion: batch/v1
kind: Job
metadata:
  name: join-train-rows
  namespace: energy
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: join
        image: ghcr.io/mskazemi/k8spodpcp:latest
        imagePullPolicy: Always
        args:
          - python3
          - join_features_labels.py
          - --features
          - /data/features.parquet
          - --labels
          - /data/labels.parquet
          - --out
          - /data/train_rows.parquet
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: podpower-data
