# ===========================================
# JOB 4: Train power prediction model
# ===========================================
---
apiVersion: batch/v1
kind: Job
metadata:
  name: train-power
  namespace: energy
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: train
        # Replace sha-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX with the commit-specific tag
        # emitted by CI for this build (ghcr.io/...:sha-<commit-sha>).
        image: ghcr.io/mskazemi/k8spodpcp:sha-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        imagePullPolicy: IfNotPresent
        args:
          - python3
          - train_power.py
          - --train
          - /data/train_rows.parquet
          - --target
          - total_energy_j
          - --out
          - /data/knn_energy.joblib
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: podpower-data
