name: cd-deploy

on:
  workflow_run:
    workflows: ["ci-build-and-push"]
    types: [completed]
    branches: ["main"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, Linux, X64]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.4.1'

      - name: Write kubeconfig
        run: |
          mkdir -p "$HOME/.kube"
          echo "${{ secrets.KUBECONFIG_CONTENTS }}" > "$HOME/.kube/config"
          chmod 600 "$HOME/.kube/config"

      - name: Set image tag in Kustomize
        run: |
          TAG=sha-${{ github.event.workflow_run.head_sha }}
          cd deploy/base
          kustomize edit set image ghcr.io/${{ github.repository }}=ghcr.io/${{ github.repository }}:$TAG

      - name: Apply prod overlay
        run: |
          kubectl apply -k deploy/overlays/prod

      - name: Wait for rollout
        run: |
          kubectl rollout status deploy/podpower-predict -n energy --timeout=180s
          kubectl rollout status deploy/podpower-collector -n energy --timeout=180s
